[package]
name = "simple_port_scanner"
version = "1.0.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
